---
name: lnk-consumer

releases:
- name: lnk
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 3
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: lnk
  azs: [z1]
  instances: 1
  jobs:
  - name: lnk
    release: lnk
    consumes:
      lnkers:
        from: zero_instance_link
        deployment: lnk
    properties:
      material: steel
  vm_type: default
  stemcell: default
  networks:
  - name: default
