---
name: lnk

releases:
- name: lnk
  version: latest
  # url: git+https://github.com/genevieve/lnk-bosh-release

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 3
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: lnk
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: lnk
    release: lnk
  vm_type: default
  stemcell: default
  networks:
  - name: default
